---
title: "philly cuisine analysis"
author: "Anna Duan"
date: "`r Sys.Date()`"
output: html_document
---

# Setup 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tigris)
library(tidyverse)
library(sf)
library(mapview)

restaurants <- st_read("working data/restaurants_raw.geojson")

neighs <- st_read("working data/phl_neighs.geojson") %>%
  st_transform(4326) %>%
  select(MAPNAME, Shape_Area) %>%
  st_make_valid()

neigh_coords <- neighs %>%
  st_centroid() %>% 
  mutate(lon = st_coordinates(.)[,1], lat = st_coordinates(.)[,2])

tracts <- tigris::tracts(state = "PA", county = "Philadelphia", year = 2018) %>%
  st_transform(4326) %>%
  select(NAME)
```


# Cuisine Groups
```{r cuisine groups}
# Updated and Refined Cuisine Keywords Dictionary
cuisine_keywords <- list(
  American = c( "american", "tradamerican", "newamerican", "comfort",
                "comfortfood", "diners", "pubs", "buffets", "steakhouses", 
                "gastropubs", "bars", "sportsbars", "salad", "bakeries",
                "lounges", "brewpubs", "beergardens", "burger", "diner",
                "cheesesteaks", "mac and cheese", "luncheonette", "chickenshop",
                "chicken_wings", "hotdogs", "wings", "cheesesteak", "steaks",
                "bbq", "barbecue", "barbeque", "smoked", "ribs", "pitmaster",
                "dog", "dogs", "fastfood", "quickbites", "burgers",
                "fries", "wraps", "pretzels", "grille", "coffee", "icecream",
                "deli", "sandwiches", "kosher", "delis", "cafes", "brunch",
                "hoagie", "brunch", "desserts", "pizza", "pizzeria",
                "pasta", "lasagna", "dessert", "rotisserie", "sweetgreen",
                "crown", "fried chicken", "cafe", "chicken", "donuts",
                "chickenwings", "fastfood", "sports", "donuts", "vegan",
                "soulfood", "southern", "soul", "cajun", "creole", "southern",
                "soul", "cajun", "creole", "cajuncreole", "tex-mex", "tex mex"
  ),
  
  East_Asian_Unspecified = c("eastasian", "pan asian", "panasian", "asian", "asian fusion", "asianfusion", "jung"),
  Chinese = c("chinese", "shanghainese", "cantonese", "dimsum", "szechuan",
              "noodles", "hotpot", "wok", "china", "garden", 
              "bubble tea", "boba", "dumpling", "wei", "meng", "dragon", "kung", 
              "canton", "mandarin", "oriental", "zheng", "xi", "jiang", "dian",
              "ho", "lam", "yang", "zhong", "shing", 
              "palace", "chen", "sai", "yong", "hou", "hong", "zhang", "jun",
              "golden", "kam", "dong", "sheng", "chung", "ping", "kon", "yi", "fuchow",
              "wah", "lee", "nanchang", "lim", "yoo", "chan", "choing", "chuong", "fujou",
              "mui", "star", "lui", "yuan", "heng", "kee", "yue", "orient","ming", "fuzhou"
              ),
  Japanese = c("japanese", "sushi", "ramen", "teppanyaki", "izakaya", "sashimi", "hibachi", "omakase", "shabu", "osaka"),
  Korean = c("korean", "bibimbap", "kimchi", "bulgogi", "kbbq", "koreanbbq", "seung", "kim"),
  Taiwanese = c("taiwanese"),
  
  Middle_Eastern_Unspecified = c("mideastern", "middle_eastern", "halal", "shawarma", "falafel", "kebab", "hummus", "arabic"),
  Turkish = c("turkish", "istanbul"),
  Egyptian = c("egyptian", "nile"),
  Syrian = c("syrian"),
  Saharan = c("saharan", "sahara"),
  Afghani = c("afghan", "afghani"),
  Moroccan = c("moroccan"),
  
  Mediterranean_Unspecified = c("mediterranean", "lebanese", "grille", "mezze"),
  Greek = c("greek", "souvlaki", "gyro", "moussaka", "baklava"),
  Spanish = c("spanish", "tapas", "paella", "iberian", "catalan", "sangria", "tapasbars"),
  Portuguese = c("portuguese"),
  Italian = c("italian", "trattoria", "pastashops", "wine_bars", "gelato", "risotto", "ristoranti", "ristorante", "giuseppe", "trazza", "tuscan"),
  
  South_Asian_Unspecified = c("curry", "tandoori", "naan", "masala", "tibet"),
  Nepalese = c("nepali", "nepalese", "himalayan"),
  Pakistani = c("pakistani", "pak", "lahore", "karachi", "punjabi", "pakistan"),
  Indian = c("indian", "indpak", "biriyani", "kerala"),

  Southeast_Asian_Unspecified = c("cambodian", "amok", "lok_lak", "southeastasian"),
  Cambodian = c("cambodian"),
  Malaysian = c("malaysian"),
  Indonesian = c("indonesian"),
  Filipino = c("filipino"),
  Thai = c("thai", "pad_thai", "thaifusion", "siam"),
  Vietnamese = c("pho", "viet", "vietnamese", "banh_mi", "pho", "bun", "pho", "springrolls", "trinh", "nguyen", "tran"),
  
  Caribbean_Unspecified = c("caribbean", "jerk", "carribean"),
  Trinidadian = c("trinidadian"),
  Haitian = c("haitian"),
  Dominican = c("dominican", "dominicanrepublic", "dominicanrepublican"),
  Jamaican = c("jamaican"),
  Puerto_Rican = c("puertorican", "borinquen"),
  Guadeloupean = c("guadeloupean", "guadalupana"),
  
  European_Unspecified = c("moderneuropean", "european", "pub","finnigan", "ulfatlar", "lagman", "east_european"),
  French = c("french", "crepe", "bistro", "brasserie", "brasseries", "patisserie", "calebasse", "creperies"),
  German = c("volksfest", "brauhaus", "german", "bratwurst", "schnitzel"),
  British = c("british", "english", "fish and chips", "fish & chips", "pub", "dandelion"),
  Irish = c("irish", "irishpub", "irishpubs"),
  Welsh = c("welsh"),
  Scottish = c("scottish"),
  Scandinavian = c("scandinavian", "swedish", "danish", "norwegian", "finnish"),
  Russian = c("russian"),
  Uzbek = c("uzbek", "plov"),
  Ukrainian = c("ukrainian"),
  Georgian = c("georgian", "khachapuri", "khinkali"),
  Polish = c("polish"),
  
  Latin_American_Unspecified = c("latin", "latinamerican", "casa", "cancun", "caldos", "restaurante", "provocan", "de jesus", "latinos"),
  Mexican = c("mexican", "tacos", "texmex", "burritos", "enchiladas", "salsa", "margaritas", "fajitas", "taqueria", "masa"),
  Nicaraguan = c("nicaraguan"),
  Salvadoran = c("salvadoran"),
  Brazilian = c("brazilian"),
  Guatemalan = c("guatemalan", "guatemalteco"),
  Colombian = c("colombian"),
  Honduran = c("honduran"),
  Venezuelan = c("venezuelan"),
  
  African_Unspecified = c("african", "jollof"),
  Senegalese = c("senegalese"),
  Ethiopian = c("ethiopian", "injera", "doro_wot", "tibs")
)

# Define cuisine priority (from highest to lowest)

cuisine_priority <- c("Taiwanese", "Uzbek", "Ukrainian", "Trinidadian", "Syrian", "Senegalese", "Scandinavian", "Russian", "Guatemalan", "Guadeloupean", "Venezuelan", "Salvadoran", "Saharan", "Nicaraguan", "Egyptian", "Pakistani", "Haitian", "Afghani", "Moroccan", "Georgian", "Filipino", "Colombian", "Malaysian", "Polish", "Turkish", "Portuguese", "Irish", "Honduran", "German", "Puerto_Rican", "Cambodian", "British", "Indonesian", "Dominican", "Brazilian", "Ethiopian", "Jamaican", "Thai", "French", "Spanish", "Greek", "Indian", "Vietnamese", "Korean", "Japanese", "Mexican", "Chinese", "Italian", "South_Asian_Unspecified", "Caribbean_Unspecified", "Middle_Eastern_Unspecified", "European_Unspecified", "African_Unspecified", "Latin_American_Unspecified", "Mediterranean_Unspecified", "East_Asian_Unspecified", "American", "Unknown")
                      
```

```{r cuisine mapping}
# Function to assign primary cuisine based on keywords with prioritization
assign_primary_cuisine <- function(name, title, alias, cuisine_dict, priority_order) {
  # Replace NA with empty string to avoid issues
  name <- ifelse(is.na(name), "", name)
  title <- ifelse(is.na(title), "", title)
  alias <- ifelse(is.na(alias), "", alias)
  
  # Combine name, title, alias for comprehensive search
  combined_text <- paste(name, title, alias, sep = " ")
  
  # Convert to lowercase for case-insensitive matching
  combined_text <- tolower(combined_text)
  
  # Iterate over each cuisine based on priority
  for (cuisine in priority_order) {
    keywords <- cuisine_dict[[cuisine]]
    
    escaped_keywords <- str_replace_all(keywords, "([.|()\\^{}+$*?]|\\[|\\]|\\\\)", "\\\\\\1")
    pattern <- paste0("\\b(", paste(escaped_keywords, collapse = "|"), ")\\b")
    
    # Check if any keyword matches
    if (grepl(pattern, combined_text)) {
      return(cuisine)
    }
  }
  
  # If no match found, return NA
  return("Unknown")
}

restaurants$cuisine <- mapply(
  assign_primary_cuisine,
  name = restaurants$name,
  title = restaurants$title,
  alias = restaurants$alias,
  MoreArgs = list(cuisine_dict = cuisine_keywords, priority_order = cuisine_priority)
)


# Remove fastfood and unknown cuisine
restaurants <- restaurants %>% filter(! name %in% c("mcdonald's", "popeye's", "kfc", "wendy's", "subway", "qdoba", "chipotle", "taco bell", "panda express", "chick fil-a")) 

unknown <- restaurants %>% filter(cuisine == "Unknown" & ! alias %in% c("seafood", "restaurants"))

# View the first few entries with the assigned cuisine
cuisine_freq <- restaurants %>%
  st_drop_geometry() %>%
  group_by(cuisine) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) 

# Cuisine groups
restaurants <- restaurants %>%
  mutate(cuisine_group = case_when(
  cuisine %in% c("Chinese", "Korean", "Japanese", "Taiwanese", "East_Asian_Unspecified") ~ "East_Asian",
  cuisine %in% c("Mexican", "Brazilian", "Honduran", "Colombian", "Nicaraguan", 
                 "Salvadoran", "Venezuelan", "Guatemalan", "Latin_American_Unspecified") ~ "Latin_American",
  cuisine %in% c("Italian", "Greek", "Spanish", "Portuguese", "Mediterranean_Unspecified") ~ "Mediterranean",
  cuisine %in% c("Indian", "Pakistani", "Himalayan", "South_Asian_Unspecified") ~ "South_Asian",
  cuisine %in% c("Vietnamese", "Thai", "Indonesian", "Cambodian", "Malaysian", "Filipino", "Southeast_Asian_Unspecified") ~ "Southeast_Asian",
  cuisine %in% c("Turkish", "Moroccan", "Afghani", "Egyptian", "Syrian", "Middle_Eastern_Unspecified") ~ "Middle_Eastern",
  cuisine %in% c("Ethiopian", "Saharan", "Senegalese", "African_Unspecified") ~ "African",
  cuisine %in% c("French", "British", "Irish", "German", "Polish", "Georgian", 
                 "Ukrainian", "Russian", "Scandinavian", "Uzbek", "European_Unspecified") ~ "European",
  cuisine %in% c("Jamaican", "Dominican", "Puerto_Rican", "Haitian", "Trinidadian", "Caribbean_Unspecified") ~ "Caribbean"))

cuisine_ranks_df <- restaurants %>% filter(!is.na(cuisine_group)) %>%
  mutate(cuisine_group = str_replace_all(cuisine_group, "_", " "),
         cuisine = str_replace_all(cuisine, "_", " "),
         name = str_to_title(name)) %>%
 group_by(cuisine_group, cuisine) %>%
  summarise(count_cuisine = n(), .groups = 'drop') %>%
  group_by(cuisine_group) %>%
  arrange(desc(count_cuisine), cuisine) %>%  
  mutate(rank = row_number()) %>%
  ungroup() %>%
  select(cuisine, rank) %>%
  st_drop_geometry() 

group_ranks_df <- restaurants %>% filter(!is.na(cuisine_group)) %>%
  mutate(cuisine_group = str_replace_all(cuisine_group, "_", " "),
         cuisine = str_replace_all(cuisine, "_", " "),
         name = str_to_title(name)) %>%
  group_by(cuisine_group) %>%
  summarise(count = n(), .groups = 'drop') %>%
  arrange(desc(count)) %>%  
  mutate(rank_group = row_number()) %>%
  ungroup() %>%
  select(cuisine_group, rank_group) %>%
  st_drop_geometry() 

restaurants_final <- restaurants %>% filter(!is.na(cuisine_group)) %>%
  mutate(cuisine_group = str_replace_all(cuisine_group, "_", " "),
         cuisine = str_replace_all(cuisine, "_", " "),
         name = str_to_title(name)) %>%
  left_join(cuisine_ranks_df, by = "cuisine") %>%
  left_join(group_ranks_df, by = "cuisine_group")

```

```{r write files}
all_group_point <- restaurants_final %>%
  select(-rank, -cuisine) %>%
  rename(rank = rank_group,
         cuisine = cuisine_group)

# cuisine_neigh <- st_intersection(restaurants_final, neighs) %>%
#   st_drop_geometry() %>%
#   left_join(neighs, by = "MAPNAME") %>%
#   group_by(cuisine_group, MAPNAME) %>%
#   summarise(count = n(), .groups = 'drop') %>%
#   group_by(MAPNAME) %>%
#   mutate(pct = 100 * count / sum(count)) %>%
#   ungroup() %>%
#   left_join(neighs, by = "MAPNAME") %>%
#   st_as_sf()

cuisine_tract <- st_intersection(restaurants_final, tracts) %>%
  st_drop_geometry() %>%
  left_join(tracts, by = "NAME") %>%
  group_by(cuisine_group, NAME) %>%
  summarise(count = n(), .groups = 'drop') %>%
  ungroup() %>%
  group_by(NAME) %>%
  mutate(pct = 100 * count / sum(count)) %>%
  ungroup() %>%
  left_join(tracts, by = "NAME") %>%
  st_as_sf()


# top_cuisine_neigh <- cuisine_neigh %>% 
#   group_by(MAPNAME) %>% 
#   slice_max(order_by = pct)


top_cuisine_tract <- cuisine_tract %>% 
  group_by(NAME) %>% 
  slice_max(order_by = pct) %>%
  ungroup() %>%
  group_by(cuisine_group) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  mutate(rank = dense_rank(desc(count))) %>%
  left_join(group_ranks_df, by = "cuisine_group") %>%
  select(-rank) %>%
  rename(rank = rank_group,
         cuisine = cuisine_group)
  

spruce_hill_rest <- neighs %>%
  filter(MAPNAME %in% c("Spruce Hill")) %>%
  st_intersection(all_group_point) %>%
  st_as_sf()

st_write(all_group_point, "data/second-slide.geojson", driver = "GeoJSON")
#st_write(restaurants_final, "data/restaurants_final.geojson", driver = "GeoJSON")
#st_write(top_cuisine_neigh, "data/top_cuisine_neigh.geojson", driver = "GeoJSON")
st_write(top_cuisine_tract, "data/third-slide.geojson", driver = "GeoJSON")
st_write(spruce_hill_rest, "data/title-slide.geojson", driver = "GeoJSON")

# Cuisine groupings
for (group in unique(restaurants_final$cuisine_group)) {
  group_data <- restaurants_final %>% filter(cuisine_group == group)
  st_write(group_data, paste0("data/", tolower(group), ".geojson"), driver = "GeoJSON")
}

```

